<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlacesSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            [
                'name' => 'Taj Mahal',
                'address' => 'Dharmapuri, Forest Colony, Tajganj',
                'city' => 'Agra',
                'country' => 'India',
                'description' => 'One of the seven wonders of the world, the Taj Mahal is a stunning white marble mausoleum built by Emperor Shah Jahan in memory of his beloved wife. This UNESCO World Heritage site is a masterpiece of Mughal architecture.',
                'imageURL' => 'TajMahal.jpg',
                'minDuration' => '2 days',
                'price' => '25000',
                'rating' => '4.9',
                'placeStatus' => 1,
                'placeType' => 'Historical',
                'latitude' => '27.1751',
                'longitude' => '78.0421',
                'phone' => '+91-562-2226431',
                'email' => 'info@tajmahal.gov.in',
                'postal_code' => '282001',
                'website' => 'https://www.tajmahal.gov.in',
            ],
            [
                'name' => 'Goa Beaches',
                'address' => 'Calangute Beach Road',
                'city' => 'Calangute, Goa',
                'country' => 'India',
                'description' => 'Famous for its pristine beaches, vibrant nightlife, water sports, and Portuguese architecture. Goa offers the perfect blend of relaxation and adventure.',
                'imageURL' => 'GoaBeaches.jpg',
                'minDuration' => '4 days',
                'price' => '30000',
                'rating' => '4.7',
                'placeStatus' => 1,
                'placeType' => 'Beach',
                'latitude' => '15.5557',
                'longitude' => '73.7517',
                'phone' => '+91-1234567890',
                'email' => 'info@goabeaches.com',
                'postal_code' => '403516',
                'website' => 'https://goabeaches.com',
            ],
            [
                'name' => 'Varanasi Ghats',
                'address' => 'Dashashwamedh Ghat Road',
                'city' => 'Varanasi',
                'country' => 'India',
                'description' => 'The spiritual capital of India, Varanasi is known for its ancient temples, holy Ganges River, and evening Ganga Aarti ceremonies. Experience the essence of Indian spirituality.',
                'imageURL' => 'VaranasiGhats.jpg',
                'minDuration' => '3 days',
                'price' => '20000',
                'rating' => '4.8',
                'placeStatus' => 1,
                'placeType' => 'Spiritual',
                'latitude' => '25.2820',
                'longitude' => '82.9563',
                'phone' => '+91-542-2392629',
                'email' => 'info@varanasi.com',
                'postal_code' => '221001',
                'website' => 'https://varanasi.nic.in',
            ],
            [
                'name' => 'Jaipur Pink City',
                'address' => 'City Palace Complex',
                'city' => 'Jaipur',
                'country' => 'India',
                'description' => 'The capital of Rajasthan, known for its stunning pink-hued buildings, magnificent palaces, and rich cultural heritage. Home to the famous Hawa Mahal and Amber Fort.',
                'imageURL' => 'JaipurPinkCity.jpg',
                'minDuration' => '3 days',
                'price' => '28000',
                'rating' => '4.6',
                'placeStatus' => 1,
                'placeType' => 'Heritage',
                'latitude' => '26.9124',
                'longitude' => '75.7873',
                'phone' => '+91-141-2618862',
                'email' => 'info@jaipurcity.com',
                'postal_code' => '302002',
                'website' => 'https://jaipur.rajasthan.gov.in',
            ],
            [
                'name' => 'Darjeeling',
                'address' => 'Mall Road',
                'city' => 'Darjeeling',
                'country' => 'India',
                'description' => 'Famous for its tea plantations, the toy train, and stunning views of the Kanchenjunga. Experience the colonial charm and natural beauty of this hill station.',
                'imageURL' => 'Darjeeling.jpg',
                'minDuration' => '4 days',
                'price' => '35000',
                'rating' => '4.7',
                'placeStatus' => 1,
                'placeType' => 'Hill Station',
                'latitude' => '27.0360',
                'longitude' => '88.2627',
                'phone' => '+91-354-2254444',
                'email' => 'info@darjeeling.com',
                'postal_code' => '734101',
                'website' => 'https://darjeeling.gov.in',
            ],
            [
                'name' => 'Darjeeling',
                'address' => 'Mall Road',
                'city' => 'Darjeeling',
                'country' => 'India',
                'description' => 'Famous for its tea plantations, the toy train, and stunning views of the Kanchenjunga. Experience the colonial charm and natural beauty of this hill station.',
                'imageURL' => 'Darjeeling.jpg',
                'minDuration' => '4 days',
                'price' => '35000',
                'rating' => '4.7',
                'placeStatus' => 2,
                'placeType' => 'Hill Station',
                'latitude' => '27.0360',
                'longitude' => '88.2627',
                'phone' => '+91-354-2254444',
                'email' => 'info@darjeeling.com',
                'postal_code' => '734101',
                'website' => 'https://darjeeling.gov.in',
            ],
            [
                'name' => 'Rishikesh',
                'address' => 'Tapovan',
                'city' => 'Rishikesh',
                'country' => 'India',
                'description' => 'Known as the Yoga Capital of the World, Rishikesh is a serene town on the banks of the Ganges, famous for its ashrams, adventure sports, and spiritual atmosphere.',
                'imageURL' => 'Rishikesh.jpg',
                'minDuration' => '3 days',
                'price' => '15000',
                'rating' => '4.6',
                'placeStatus' => 0,
                'placeType' => 'Spiritual',
                'latitude' => '30.0869',
                'longitude' => '78.2676',
                'phone' => '+91-135-2431793',
                'email' => 'info@rishikesh.com',
                'postal_code' => '249192',
                'website' => 'https://rishikesh.uk.gov.in',
            ],
            [
                'name' => 'Hampi',
                'address' => 'Hampi Bazaar',
                'city' => 'Hampi',
                'country' => 'India',
                'description' => 'A UNESCO World Heritage Site, Hampi is known for its ancient ruins, temples, and boulder-strewn landscape, offering a glimpse into the Vijayanagara Empire.',
                'imageURL' => 'Hampi.jpg',
                'minDuration' => '2 days',
                'price' => '11000',
                'rating' => '4.5',
                'placeStatus' => 0,
                'placeType' => 'Heritage',
                'latitude' => '15.3350',
                'longitude' => '76.4600',
                'phone' => '+91-8394-241339',
                'email' => 'info@hampi.com',
                'postal_code' => '583239',
                'website' => 'https://hampi.in',
            ],
            [
                'name' => 'Andaman Islands',
                'address' => 'Port Blair',
                'city' => 'Port Blair',
                'country' => 'India',
                'description' => 'A tropical paradise, the Andaman Islands are famous for their pristine beaches, crystal-clear waters, and vibrant marine life, perfect for snorkeling and relaxation.',
                'imageURL' => 'AndamanIslands.jpg',
                'minDuration' => '5 days',
                'price' => '35000',
                'rating' => '4.8',
                'placeStatus' => 2,
                'placeType' => 'Beach',
                'latitude' => '11.6234',
                'longitude' => '92.7265',
                'phone' => '+91-3192-232695',
                'email' => 'info@andaman.gov.in',
                'postal_code' => '744101',
                'website' => 'https://andaman.gov.in',
            ],
            [
                'name' => 'Ranthambore National Park',
                'address' => 'Sawai Madhopur',
                'city' => 'Ranthambore',
                'country' => 'India',
                'description' => 'One of the largest national parks in northern India, Ranthambore is renowned for its tiger reserve, ancient fort, and diverse wildlife.',
                'imageURL' => 'Ranthambore.jpg',
                'minDuration' => '2 days',
                'price' => '18000',
                'rating' => '4.7',
                'placeStatus' => 2,
                'placeType' => 'Wildlife',
                'latitude' => '26.0173',
                'longitude' => '76.5026',
                'phone' => '+91-7462-220495',
                'email' => 'info@ranthamborenationalpark.com',
                'postal_code' => '322001',
                'website' => 'https://ranthamborenationalpark.com',
            ],
        ];

        foreach ($places as $place) {
            DB::table('places')->insert($place);
        }
    }
} 